### ISSUE TITLE
International Women's Day

### ISSUE THREAD

**Issue by markus-gellrich** [MicMun/DeuFeiTage#5]
March 8th doesn't show up in Berlin

**Comment by markus-gellrich** [comment]
i already coded, how push?

**Comment by MicMun** [comment]
I do that on my own, thank you.
It not that much to code (i have a configuration file for this).

**Comment by markus-gellrich** [comment]
yeah found the json and comiited the changes inlc description

 {
      "ID": 18,
      "Name": "International Women's Day",
      "States": [
        "BE"
      ],
      "Description": "International Women's Day is a public holiday in some countries and largely ignored elsewhere. In some places, it is a day of protest; in others, it is a day that celebrates womanhood. Berlin made it a public holiday in early 2019
"
}

 {
      "ID": 18,
      "Name": "Internationaler Frauentag",
      "States": [
        "BE"
      ],
      "Description": "Der International Frauentag ist in einigen Ländern gesetzlicher Feiertag, aber wird anderswo weitgehend ignoriert. An manchen Orten ist es ein Tag des Protests; andernorts ist es ein Tag die Weiblichkeit zu feiern. Das Berliner Abgeordnetenhaus beschloss im Januar 2019 den gesetzlichen Feiertag.
"
}

**Comment by MicMun** [comment]
I have finished it yet in Release 4.2.0.
I put it into Google Play and hope, that F-Droid updates also.

**Comment by markus-gellrich** [comment]
Thanks a lot, you do great.
