### ISSUE TITLE
[Idea] Register system calendar

### ISSUE THREAD

**Issue by utack** [MicMun/DeuFeiTage#6]
Hi,
thank you for this app!
I have an idea how to expand its usage:
The app could register a new system calendar containing all the holidays.
This way its content would be displayed in any calendar app.
It is probably quite a bit of work, but maybe you find time for it.
DAVx⁵ should have code that does this as example
https://gitlab.com/bitfireAT/davx5-ose
Thank you for consideration!

**Comment by MicMun** [comment]
Hi,
that might be a great idea. But there are already possible solutions for calendars with holiday apps.
It would also be the question of whether you enter only the currently set state, or indeed all holidays.

But I think about it.

**Comment by just-Nob** [comment]
Wanted to open a ticket with the same suggestion. ;)
For me, DeuFeiTage raised its value of about 200% or even more, if it had an own local Android calendar to write its German public holidays to.
For example, the two apps "Birthday Adapter" and "Birthday Calendar" (both also on F-Droid) do it the same way, but for another issue: Once a day, they grab all current contract entries, gathering all birthdays (and other yearly events) to collect them into an own, local calendar. So all contacts' birthdays could be displayed in any calendar app.
For DeuFeiTage, an automatic update once a month would be sufficient.
Would be great if that feature would be implemented! :)

**Comment by MicMun** [comment]
I think about it. It isn't easy with selected state and how it works with changing year.
But I have a few free days next week, so I can look at this feature.

**Comment by MicMun** [comment]
> The app could register a new system calendar containing all the holidays.
> This way its content would be displayed in any calendar app.

Do you want this for the selected state of germany or for all holidays of germany? How do you expect the change of the selected state in the system calendar?

There are also sites like https://www.ferienwiki.de/exports/de, where you can include the ical calendar in any calendar app. So perhaps it is not necessary that my app has this feature.

**Comment by utack** [comment]
Google also has a Calendar of Public Holidays, continuously updated  
https://calendar.google.com/calendar/embed?src=de.german%23holiday%40group.v.calendar.google.com&ctz=Europe%2FBerlin  
It works in ICSx5:  
https://calendar.google.com/calendar/ical/de.german%23holiday@group.v.calendar.google.com/public/basic.ics  
  
So I do not really "depend" on this app doing it, it was just an idea if you want to extend it.

**Comment by just-Nob** [comment]
The Google calendar only works if you synchronize your calendars with your Google account, I guess?
I don't do so.

**Comment by utack** [comment]
Works in ICSx5 for me  
https://f-droid.org/de/packages/at.bitfire.icsdroid/

**Comment by MicMun** [comment]
Because it is difficult to implement and there are other solutions for that, I will not implement this.
