### ISSUE TITLE
Add holidays common and not common to all states

### ISSUE THREAD

**Issue by SantosSi** [MicMun/DeuFeiTage#8]
common holidays = "bundeseinheitliche Feiertage"
Currently there is no easy way of knowing what holidays are common to the whole repulic.
Imagine why I request this feature today :-)

**Comment by MicMun** [comment]
I implement the feature in the way, that there are two new choices in the list of states:
- All holidays
- Common holidays

Also at the holidays there is a list of states, which have the holiday or DE for common holiday.
The states are listed as a shortcut (BY = Bayern, SN = Sachsen, SH = Schleswig-Holstein, ...).
